version: '2.3'

# https://github.com/nvidia/nvidia-container-runtime#environment-variables-oci-spec
services:
  milvusdb:
    image: milvusdb/milvus:0.7.0-cpu-d031120-de409b
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 19530:19530
      - 19121:19121
      - 9091:9091
    volumes:
      - ${MILVUS_HOME}/db:/var/lib/milvus/db
      - ${MILVUS_HOME}/conf:/var/lib/milvus/conf
      - ${MILVUS_HOME}/logs:/var/lib/milvus/logs
      - ${MILVUS_HOME}/wal:/var/lib/milvus/wal
  python-user:
    build: .
    volumes:
      - ../src:/workdir
    working_dir: /workdir
    command: python example.py
    depends_on:
      - milvusdb