version: '2.3'

networks:
  monitor:
    driver: bridge
  application:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./server_down.yml:/etc/prometheus/node_down.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor

  milvus_server:
    container_name: milvus_server
    # runtime: nvidia
    # image: milvusdb/milvus:latest
    image: milvusdb/milvus:0.7.0-cpu-d031120-de409b
    restart: always
    links:
      - prometheus
    environment:
      WEB_APP: host.docker.internal
    volumes:
      - ${MILVUS_HOME}/conf/server_config.yaml:/var/lib/milvus/conf/server_config.yaml
      - ${MILVUS_HOME}/conf/log_config.conf:/var/lib/milvus/conf/log_config.conf
    ports:
      - "8080:8080"
      - "19530:19530"
    networks:
      - monitor
      - application

  app:
    build: .
    container_name: app_container
    volumes:
      - ../src:/workdir
    working_dir: /workdir
    command: ./test_python.sh
    networks:
      - application
    depends_on:
      - milvus_server